[build]
command = "npm run build"
publish = "out"
base = "/"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "./out" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 