name = "greenwich-institute-website"
output = "standalone"

# Configure custom domain
routes = [
  { pattern = "greenwich-institute.com", custom_domain = true }
]

# Add compatibility settings
compatibility_date = "2024-05-01"
compatibility_flags = [] 