name = "greenwich-institute-website"

# Configure build settings for Next.js
main = "./.next/server/pages/index.js"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
output_directory = ".next"

[site]
bucket = "./.next/static"

# Configure custom domain
routes = [
  { pattern = "greenwich-institute.com", custom_domain = true }
]

[env.production]
workers_dev = true 