name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare for Cloudflare Pages
        run: |
          mkdir -p .next/standalone/public
          cp -r .next/static .next/standalone/.next/
          cp -r public/* .next/standalone/public/
          
      - name: Create routes.json file
        run: |
          echo '{
            "version": 1,
            "include": ["/*"],
            "exclude": ["/images/*", "/fonts/*", "/_next/*"]
          }' > .next/standalone/_routes.json

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.PROJECT_NAME || 'greenwich-institute-new' }}
          directory: .next/standalone
          gitHubToken: ${{ secrets.GITHUB_TOKEN }} 